---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8sniff-config
  namespace: {{ $.Values.k8sniff.namespace }}
data:
  config.json: |-
    {
        "bind": {
            "host": "0.0.0.0",
            "port": 443
        },
        "kubernetes": {}
    }
