{{ if $.Values.k8sniff.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sniff
  namespace: {{ $.Values.k8sniff.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sniff-{{ $.Values.k8sniff.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8sniff
subjects:
- kind: ServiceAccount
  name: k8sniff
  namespace: {{ $.Values.k8sniff.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8sniff
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - ingresses
      - services
    verbs:
      - get
      - watch
      - list
{{ end }}
